server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:licensedb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url: zipkin:9411
  sleuth:
    sampler:
      percentage: 1  
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/      
 
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    
example:
  property: I am the dev with default

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeinHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - java.util.concurrent.TimeoutException
          
keycloak:
  realm: ostock-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: LIO5yAVHbAbLLOZGGr1ygXO9QFtAQEa8
  use-resource-role-mappings: true
  bearer-only: true          
