spring:
  datasource:
    url: jdbc:h2:mem:licensedb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}2838334c2e5e27f75c8b99c79aed838c062f4601fda128faea99dbe95cd130eb'
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    
example:
  property: I am the dev with default
