server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:organizationdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
keycloak:
  realm: ostock-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: LIO5yAVHbAbLLOZGGr1ygXO9QFtAQEa8
  use-resource-role-mappings: true
  bearer-only: true
zipkin:
  base-url: zipkin:9411  
