management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
spring:
  cloud:
    gateway:
      discovery:
          locator:
            enabled: false
            lower-case-service-id: true
