server:
  port: 8090
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
spring:
  cloud:
    gateway:
      discovery:
          locator:
            enabled: false
            lower-case-service-id: true
  zipkin:
    base-url: zipkin:9411             
            
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/            
